In [ ]:
# NumPy - Matrizes, p1

In [ ]:
# 1. Objeto de Matriz Multidimensional
# 2. Variedade de rotinas para operações rápidas em matrizes
# 3. Tem um tamanho fixo desde a criação
# 4. Os elementos devem ser todos do mesmo tipo
# 5. Há a necessidade de fazer importação da biblioteca numpy

In [2]:
# Importação de bibliotecas

import numpy as np

In [4]:
# Criar uma matriz de uma dimensão

a = np.array([12, 34, 26, 18, 10]) 
print(a)



[12 34 26 18 10]


In [10]:
# Determinar o tipo dos elementos da matriz usando dtype e type


# a.dtype()
# type(a)

numpy.ndarray

In [ ]:
# Obs:
# dtype -> Forma de verificar o tipo de um atributo, ou seja, não é uma função
# type() -> Método nativo para verificar o tipo

In [4]:
# Criar a array com um tipo específico (pode ser float64)


# uFloat = np.array([1, 2, 3], dtype = np.float64)
# uInt = np.array([5, 8, 9], dtype = np.int32)

# print(uFloat)
# print(uInt)

float64
[1. 2. 3.]


In [19]:
# Mudar o tipo de array


# mType = np.array([5, 6, 7])
# print(mType)

# floatType = mType.astype(np.float64)
# print(floatType)

int32 
 float64


In [5]:
# Criar uma matriz bidimensional


# bm = np.array([[8, 5, 6], [4, 6, 8], [9, 6, 1]])
# print(bm)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# p2

In [3]:
# Importação de bibliotecas

import numpy as np

In [ ]:
# Criar arrays vazios 
# tipificados - empty significa que não são inicializados, não que são vazios
# indicar as dimensões


# a = np.empty([3,2], dtype = np.int32)
# print(a)

In [ ]:
# Criar uma matriz  4x3 com valores zero


# b = np.zeros([4,3], dtype = np.int32)
# print(b)

In [ ]:
# Criar uma matriz com valores iguais a 1


# c = np.ones([5, 4], dtype = np.int32)
# print(c)

In [ ]:
# Criar matriz quadrada com diagonal principal com valores 1 e os outros valores zero


oi = np.eye(4, dtype = np.int32)
oi
# d = np.eye(5)
# print(d)

# Obs: Só é possível em matrizes quadráticas

In [1]:
# Impotação de bibliotecas

import numpy as np

In [ ]:
# Criar matriz com valores aleatórios entre zero e um


# ale1 = np.random.random(5)
# print(ale1)

# ale1 = np.random.random(([5, 5])) ***

In [4]:
# Criar matriz com valores aleatórios distr. normal contendo negativos


# ale2 = np.random.randn((5))
# print(ale2)

array([ 1.93745235, -1.23096542,  0.16579195,  0.91250671, -0.18450583])

In [ ]:
# Criar matriz com valores aleatórios, matriz 3 x 4, multiplicando os valores por dez


# ale3 = (10*np.random.random([3, 4]))
# print(ale3)

In [8]:
# Criar matriz de numeros inteiros, limitando os valores até 10, dimensões (3, 4)


inteiros = np.random.randint(10, size = (3, 4))
inteiros

array([6, 2, 7, 2])

In [ ]:
# USO DE SEMENTE

In [10]:
# Criar uma semente


gnr = np.random.default_rng(1)

In [14]:
# Criar matriz de números inteiros usando a semente, limitando os números até 10


a = gnr.integers(10, size = (3, 4))
print(a)

[[8 3 4 7]
 [1 3 1 4]
 [9 1 3 4]]


In [12]:
# Gerar números aleatórios usando a semente


# ale4 = gnr.random(3)
# print (ale4)

# ou
# a = gnr.random(size=(3,3))
# a

array([[0.94864945, 0.31183145, 0.42332645],
       [0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [1]:
import numpy as np

In [2]:
# remover repetições 


a = np.array([1, 2, 3, 4, 1, 5, 2, 5])
j = np.unique(a)
print(a, j)

[1 2 3 4 1 5 2 5] [1 2 3 4 5]


In [7]:
# remover repetições retornando a quantidade de elementos não repetidos

lista = [1,2,3,1,2,3,1,2,3,1,2,3,2,3,3]

unicos, quantidade = np.unique(lista, return_counts=True)

print('lista -> ', lista)
print('unicos -> ', unicos)
print('quantidade -> ', quantidade)

lista ->  [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 3, 3]
unicos ->  [1 2 3]
quantidade ->  [4 5 6]


In [ ]:
# FUNÇÕES ESPECÍFICAS, p3

In [1]:
# Importação de bibliotecas

import numpy as np

In [ ]:
# Criar matriz bidimensional k, com números inteiros, usando uma semente, tamanho 10, 3 x 3


# gnr = np.random.default_rng(1)
# k = gnr.integers(10, size = (3, 3))
# print(k)

In [ ]:
# Criar matriz bidimensional 3 x 3 de números inteiros


# k = np.array([[5, 8, 6], [9, 4, 6], [7, 5, 2]])
# print(k)

In [ ]:
# Criar matriz bidimencional 10 x 3 com numeros inteiros, aleatorios de valor máximo 10:


# matriz_aleatoria = np.random.randint(10, size=(10,3))
# matriz_aleatoria

In [4]:
# Encontrar as indices com o maior valor em cada linha da matriz aleatoria


# matriz_aleatoria_indices_maiores = [np.argmax(t) for t in matriz_aleatoria]
# matriz_aleatoria_indices_maiores

[0, 0, 0]

In [11]:
k

array([[4, 5, 7],
       [9, 0, 1],
       [8, 9, 2]], dtype=int64)

In [14]:
# mostrar elemento específico da matriz k 


# print(k[1][1])

5

In [ ]:
# Mostrar o tamanho das dimensões da matriz k


# print(k.shape)

In [ ]:
# FUNÇÕES MATEMÁTICAS:

In [ ]:
# Mostrar o maior valor da matriz


# print(k.max())

In [ ]:
# Mostrar o menor valor da matriz


# print(k.min())

In [ ]:
# Mostrar a soma dos valores da matriz


# print(k.sum())

In [ ]:
# Mostrar o valor médio dos valores da matriz


# print(k.mean())

In [ ]:
# Mostrar o valor do desvio padrão (standard deviation) dos valores da matriz


# print(k.std())

In [ ]:
# Funções universais - aplicadas a todos os elementos da matriz - , p4

In [ ]:
# Importação de bibliotecas

import numpy as np

In [ ]:
# Criar matriz com quadrados perfeitos


# a = np.array([1, 4, 9, 16, 25, 36, 49])
# print(a)

In [ ]:
# Mostrar o valor da raiz quadrada de todos os elementos da matriz


# print(np.sqrt(a))

In [ ]:
# Mostrar o valor do exponencial de todos os elementos da matriz


# print(np.exp(a))

In [ ]:
# Crie matriz com números inteiros


# b = np.array([1, 2, 3, 4, 5, 6])
# print(b)

In [ ]:
# Mostrar o elemento na posição 2


# print(b[2])

In [ ]:
# Mostrar o array criado a partir da posição 0 até o segundo elemento


# print(b[0:2])

In [ ]:
# Mostrar todo o array a partir da 2ª posição


# print(b[2:])

In [ ]:
# Mostrar o array a partir da antepenúltima posição até o final


# print(b[-3:])

In [ ]:
# Extração de Linhas e Colunas

In [ ]:
# Crie matriz bidimensional shape: 3 x 3


# a = np.array([[4, 6, 8], [2, 8, 9], [5, 7, 1]])
# print(a)
# print('----------')

In [ ]:
# Print da primeira linha com todas as colunas


# print(a[0, :])

In [ ]:
# Print da segunda linha com todas as colunas


# print(a[1, :])

In [ ]:
# Print da terceiralinha com todas as colunas 


# print(a[2, :])

In [ ]:
# Print de todas as linhas da primeira coluna


# print(a[:, 0])

In [ ]:
# print de todas as linhas  da segunda coluna


# print(a[:, 1])

In [ ]:
# print de todas as linhas  da terceira coluna


# print(a[:, 2])

In [ ]:
# Adição e multiplicação de matrizes, p5

In [2]:
# Importação de bibliotecas

import numpy as np

In [3]:
# Criar duas matrizes inteiros, shape: 3 x 3


a = np.array([[1, 9, 6], [8, 2, 6], [7, 5, 4]])
# b = np.array([[5, 6, 8], [4, 6, 7], [1, 6, 2]])

# print(a)
# print(b)

In [ ]:
# Some as duas matrizes Criadas


# soma1 = a + b
# print(soma1)

In [ ]:
# Multiplique as duas matrizes criadas


# mult1 = a * b
# print(mult1)

In [4]:
# Criar uma matriz vetor com três elementos: 


c = np.array([1, 2, 3])
# print(c)

In [ ]:
# Some uma matriz anterior a essa nova


# soma2 = a + c
# print(soma2)

In [ ]:
# Multiplique uma matriz anterior a nova


# mult2 = b * c
# print(mult2)

In [ ]:
# TRANSPOSIÇÃO - Rearranjar a matriz transpondo as linhas em colunas e as colunas em linhas
# Obs: Não há necessidade de instanciar a matriz, pois o método cria a matriz sozinho

In [ ]:
# Instanciar uma matriz utilizando um método, passando apenas o shape (arange - reshape)


# a = np.arange(15).reshape((5, 3))

# print(a)

In [ ]:
# Instanciar um conjunto de 15 elementos 3 x 5, de 0 a 14 em 3 linhas e 5 colunas - Transpor usando T


# b = np.arange(15).reshape((3, 5))
# print(b)

In [ ]:
# Transpor a matriz b usando método T


# c = b.T
# print(c)

In [ ]:
# Transpor a matriz a usando método transpose

# t = a.transpose((b))

# d = a.transpose((1, 0))
# print(d)

In [ ]:
# EXPRESSÕES LÓGICAS

In [ ]:
# Importação das bibliotecas

import numpy as np

In [17]:
# Criar matriz com valores aleatórios, positivos e negativos (distribuição normal)


# a = np.random.randn(5, 5)
# print(a)

array([[-0.48089116, -0.07515221, -1.17046989,  1.04636322, -0.19687512],
       [-0.37704007,  3.23896566,  0.37784114, -0.62346404,  1.76082615],
       [ 0.62850704, -0.63391546, -0.04592633,  0.96360434, -0.82612188]])

In [18]:
# Criar uma matriz de elementos booleanos, que seja verdadeira sempre que (a) for maior que (0)


# x = (a > 0)
# print(x)

array([[False, False, False,  True, False],
       [False,  True,  True, False,  True],
       [ True, False, False,  True, False]])

In [ ]:
# Usando Where
# Criar matriz com número 1 para x > 0 e -1 x < 0


# a = np.where(x > 0, 1, -1)
# print(a)

In [29]:
x

array([[ 1.00526717, -1.51514491,  1.02877425,  0.4796862 ,  1.88451517],
       [-0.18323732,  0.83367001,  1.11445076, -0.12765584, -0.3176924 ],
       [-1.20258961,  0.85322505, -0.32132831,  0.13779201,  0.23791987]])